kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: node:16-alpine
    commands:
      - apk add --no-cache python3 make g++
      - npm ci
      - npm run build

  - name: test
    image: node:16-alpine
    commands:
      - npm ci
      - npm test

  - name: docker_build
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: your-dockerhub-username/uptime-kuma
      tags:
        - latest
        - ${DRONE_COMMIT_SHA}
      dockerfile: Dockerfile

trigger:
  event:
    - push
    - tag
